pipeline:
    name: trialpipeline
    identifier: trialpipeline
    projectIdentifier: Org01_Proj01
    orgIdentifier: Org01
    tags: {}
    properties:
        ci:
            codebase:
                connectorRef: yash
                repoName: firstdrone
                build: <+input>
    stages:
        - stage:
              name: buildtrial
              identifier: buildtrial
              description: ""
              type: CI
              spec:
                  cloneCodebase: true
                  infrastructure:
                      type: KubernetesHosted
                      spec:
                          identifier: k8s-hosted-infra
                  execution:
                      steps:
                          - step:
                                type: BuildAndPushDockerRegistry
                                name: dock
                                identifier: dock
                                spec:
                                    connectorRef: new_connector
                                    repo: yashaswi11/doc
                                    tags:
                                        - version
        - stage:
              name: deployed
              identifier: deployed
              description: ""
              type: Deployment
              spec:
                  serviceConfig:
                      serviceRef: trainingservice
                      serviceDefinition:
                          spec:
                              variables: []
                              manifests:
                                  - manifest:
                                        identifier: main
                                        type: K8sManifest
                                        spec:
                                            store:
                                                type: Github
                                                spec:
                                                    connectorRef: yash
                                                    gitFetchType: Branch
                                                    paths:
                                                        - content/en/examples/application/nginx-app.yaml
                                                    repoName: website
                                                    branch: main
                                            skipResourceVersioning: false
                              artifacts:
                                  primary:
                                      spec:
                                          connectorRef: new_connector
                                          imagePath: library/nginx
                                          tag: <+input>
                                      type: DockerRegistry
                          type: Kubernetes
                  infrastructure:
                      environmentRef: trainingenvironment
                      infrastructureDefinition:
                          type: KubernetesDirect
                          spec:
                              connectorRef: delegate
                              namespace: harness-delegate-ng
                              releaseName: release-<+INFRA_KEY>
                      allowSimultaneousDeployments: false
                  execution:
                      steps:
                          - step:
                                name: Rollout Deployment
                                identifier: rolloutDeployment
                                type: K8sRollingDeploy
                                timeout: 10m
                                spec:
                                    skipDryRun: false
                      rollbackSteps:
                          - step:
                                name: Rollback Rollout Deployment
                                identifier: rollbackRolloutDeployment
                                type: K8sRollingRollback
                                timeout: 10m
                                spec: {}
              tags: {}
              failureStrategies:
                  - onFailure:
                        errors:
                            - AllErrors
                        action:
                            type: StageRollback
