pipeline:
    name: Build dockerfile
    identifier: Build_dockerfile_1660300111177
    projectIdentifier: Org01_Proj01
    orgIdentifier: Org01
    properties:
        ci:
            codebase:
                connectorRef: account.Github
                repoName: Yashaswishrm/dockerfile
                build: <+input>
    stages:
        - stage:
              name: Build
              identifier: Build
              type: CI
              spec:
                  cloneCodebase: true
                  infrastructure:
                      type: KubernetesHosted
                      spec:
                          identifier: k8s-hosted-infra
                  execution:
                      steps:
                          - step:
                                type: Run
                                name: Echo Welcome Message
                                identifier: Run
                                spec:
                                    connectorRef: account.harnessImage
                                    image: alpine
                                    shell: Sh
                                    command: 'echo "Welcome to Harness CI" '
                          - step:
                                type: BuildAndPushDockerRegistry
                                name: doc
                                identifier: doc
                                spec:
                                    connectorRef: new_connector
                                    repo: yashaswi11/doc
                                    tags:
                                        - version
        - stage:
              name: deploy
              identifier: deploy
              description: ""
              type: Deployment
              spec:
                  serviceConfig:
                      serviceRef: trainingservice
                      serviceDefinition:
                          spec:
                              variables: []
                              manifests:
                                  - manifest:
                                        identifier: trial
                                        type: K8sManifest
                                        spec:
                                            store:
                                                type: Github
                                                spec:
                                                    connectorRef: yash
                                                    gitFetchType: Branch
                                                    paths:
                                                        - content/en/examples/application/nginx-app.yaml
                                                    repoName: website
                                                    branch: main
                                            skipResourceVersioning: false
                          type: Kubernetes
                  infrastructure:
                      environmentRef: trainingenvironment
                      infrastructureDefinition:
                          type: KubernetesDirect
                          spec:
                              connectorRef: delegate
                              namespace: harness-delegate-ng
                              releaseName: release-<+INFRA_KEY>
                      allowSimultaneousDeployments: false
                  execution:
                      steps:
                          - step:
                                name: Rollout Deployment
                                identifier: rolloutDeployment
                                type: K8sRollingDeploy
                                timeout: 10m
                                spec:
                                    skipDryRun: false
                      rollbackSteps:
                          - step:
                                name: Rollback Rollout Deployment
                                identifier: rollbackRolloutDeployment
                                type: K8sRollingRollback
                                timeout: 10m
                                spec: {}
              tags: {}
              failureStrategies:
                  - onFailure:
                        errors:
                            - AllErrors
                        action:
                            type: StageRollback
