pipeline:
    name: Org03_Proj03_pipeline03
    identifier: Org03_Proj03_pipeline03
    projectIdentifier: Org01_Proj01
    orgIdentifier: Org01
    tags: {}
    stages:
        - stage:
              name: approval02
              identifier: approval02
              description: ""
              type: Approval
              spec:
                  execution:
                      steps:
                          - step:
                                name: approv
                                identifier: approv
                                type: HarnessApproval
                                timeout: 1d
                                spec:
                                    approvalMessage: |-
                                        Please review the following information
                                        and approve the pipeline progression
                                    includePipelineExecutionHistory: true
                                    approvers:
                                        minimumCount: 1
                                        disallowPipelineExecutor: false
                                        userGroups:
                                            - UG
                                    approverInputs: []
              tags: {}
        - stage:
              name: build03
              identifier: build03
              description: ""
              type: CI
              spec:
                  cloneCodebase: true
                  execution:
                      steps:
                          - step:
                                type: BuildAndPushDockerRegistry
                                name: doc
                                identifier: doc
                                spec:
                                    connectorRef: new_connector
                                    repo: yashaswi11/cronojobrepo
                                    tags:
                                        - version
                  infrastructure:
                      type: KubernetesHosted
                      spec:
                          identifier: k8s-hosted-infra
    properties:
        ci:
            codebase:
                connectorRef: yash
                repoName: firstdrone
                build: <+input>
